### PR TITLE
Fixes #13 Fix threading issue in local inject

### LINKED ISSUE #13: Address Service Dictionary Threading issues
We should also address the thread safety issues around the `localServiceDict` in `WhoopDI`.

The `localServiceDict` is not thread safe and can be mutated across multiple threads leading to crashes when it is deallocated. 

This happens when one thread does a local injection and another thread is doing a separate injection at the same time.

### PR DESCRIPTION
**Pull request by ncipollo**
- Add thread safety around local service dictionary in container.
- Adds mechanism to provide options / flags to WhoopDI so this functionality can be safely rolled out.

### CODE REVIEW

File: Tests/WhoopDIKitTests/Container/ContainerTests.swift [hunk 1]
```diff
@@ -1,60 +1,94 @@
...
             // Typically you'd override or provide a transient dependency. I'm using the top level dependency here
             // for the sake of simplicity.
             module.factory(name: "C_Factory") { DependencyA() as Dependency }
         }
-        XCTAssertTrue(dependency is DependencyA)
+        #expect(dependency is DependencyA)
+    }
+    
+    @Test(.bug("https://github.com/WhoopInc/WhoopDI/issues/13"))
+    func inject_localDefinition_concurrency() async {
```
Comment (ncipollo) [inline Tests/WhoopDIKitTests/Container/ContainerTests.swift:47]: If you disable the thread safety option then run this 1000 times you will hit the race condition / crash. When you enable it and do the same you should no loner see the crash.

File: Sources/WhoopDIKit/Container/Container.swift [hunk 2]
```diff
@@ -54,28 +60,30 @@ public final class Container {
...
                           params: Any? = nil,
                           _ localDefinition: (DependencyModule) -> Void) -> T {
-        guard localServiceDict == nil else {
+        guard !isLocalInjectActive else {
             fatalError("Nesting WhoopDI.inject with local definitions is not currently supported")
         }
+        
+        isLocalInjectActive = true
+        defer {
+            isLocalInjectActive = false
```
Comment (jrosen081) [inline Sources/WhoopDIKit/Container/Container.swift:69]: Could this not also have a memory safety race? I wonder if we should have this be part of the `ThreadSafeDependencyGraph` and ony check that

File: Sources/WhoopDIKit/Container/Container.swift [hunk 3]
```diff
@@ -54,28 +60,30 @@ public final class Container {
...
+            localDependencyGraph.resetDependencyGraph()
+        }
         // We need to maintain a reference to the local service dictionary because transient dependencies may also
         // need to reference dependencies from it.
         // ----
-        // This is a little dangerous since we are mutating a static variable but it should be fine as long as you
+        // This is a little dangerous since we are mutating a variable but it should be fine as long as you
```
Comment (jrosen081) [inline Sources/WhoopDIKit/Container/Container.swift:75]: yeah this makes me think we should lock this too

File: Sources/WhoopDIKit/Container/Container.swift [hunk 4]
```diff
@@ -54,28 +60,30 @@ public final class Container {
...
-            return try get(name, params)
-        } catch {
-            fatalError("WhoopDI inject failed with error: \(error)")
+        return localDependencyGraph.aquireDependencyGraph { localServiceDict in
+            let localModule = DependencyModule()
+            localDefinition(localModule)
+            localModule.addToServiceDictionary(serviceDict: localServiceDict)
+            
+            do {
+                return try get(name, params)
```
Comment (jrosen081) [inline Sources/WhoopDIKit/Container/Container.swift:83]: I wonder if this is better than the crash before

File: Tests/WhoopDIKitTests/Container/ContainerTests.swift [hunk 5]
```diff
@@ -1,60 +1,94 @@
-import XCTest
+import Testing
 @testable import WhoopDIKit
 
-class ContainerTests: XCTestCase {
-    private let container = Container()
+// This is unchecked Sendable so we can run our local inject concurrency test
+@Suite(.serialized)
```
Comment (jrosen081) [inline Tests/WhoopDIKitTests/Container/ContainerTests.swift:5]: Do these need to be serialized?

File: Tests/WhoopDIKitTests/Container/ContainerTests.swift [hunk 6]
```diff
@@ -1,60 +1,94 @@
...
+        #expect(dependency is DependencyA)
+    }
+    
+    @Test(.bug("https://github.com/WhoopInc/WhoopDI/issues/13"))
+    func inject_localDefinition_concurrency() async {
+        // You can run this test repeatedly to verify we don't have a concurrency issue when
+        // performing a local inject. 1000 times should do the trick.
+        container.registerModules(modules: [GoodTestModule()])
+        
+        async let resultA = Task {
```
Comment (jrosen081) [inline Tests/WhoopDIKitTests/Container/ContainerTests.swift:52]: nit we don't need `async let` here if we are creating a `Task`. We likely want a `Task.detached` to make sure it goes into the default thread pool

File: Sources/WhoopDIKit/Container/Container.swift (hunk 2 above)
Comment (ncipollo) [reply Sources/WhoopDIKit/Container/Container.swift:69]: _maybe_? I think boolean updates are atomic but let me do some research on this.

Comment (ncipollo) [reply Sources/WhoopDIKit/Container/Container.swift:69]: Oh nevermind I see what you are saying.

File: Sources/WhoopDIKit/Container/Container.swift (hunk 4 above)
Comment (ncipollo) [reply Sources/WhoopDIKit/Container/Container.swift:83]: What do you mean by this?

File: Sources/WhoopDIKit/Container/Container.swift (hunk 2 above)
Comment (nathanbeaumont) [reply Sources/WhoopDIKit/Container/Container.swift:69]: ➕ This looks like, we can hit the fatalError above here.

File: Sources/WhoopDIKit/Container/Container.swift [hunk 7]
```diff
@@ -54,28 +60,30 @@ public final class Container {
...
+            } catch {
+                fatalError("WhoopDI inject failed with error: \(error)")
```
Comment (nathanbeaumont) [inline Sources/WhoopDIKit/Container/Container.swift:85]: While we are here, can we pack more info into this error message. i.e. the name and params. If we don't already print this somewhere

File: Sources/WhoopDIKit/Container/Container.swift (hunk 2 above)
Comment (ncipollo) [reply Sources/WhoopDIKit/Container/Container.swift:69]: I'll move this down into the `aquireDependencyGraph` block which is internally protected by a recursive lock.

File: Sources/WhoopDIKit/Options/DefaultOptionProvider.swift [hunk 8]
```diff
@@ -0,0 +1,9 @@
+struct DefaultOptionProvider: WhoopDIOptionProvider {
+    func isOptionEnabled(_ option: WhoopDIOption) -> Bool {
+        false
```
[the remark this answers is not in the document]
Comment (ncipollo) [reply Sources/WhoopDIKit/Options/DefaultOptionProvider.swift:3]: Why? The intent is to default everything to false.

File: Tests/WhoopDIKitTests/Container/ContainerTests.swift (hunk 5 above)
Comment (ncipollo) [reply Tests/WhoopDIKitTests/Container/ContainerTests.swift:5]: Negative.

File: Sources/WhoopDIKit/Container/Container.swift (hunk 4 above)
Comment (jrosen081) [reply Sources/WhoopDIKit/Container/Container.swift:80]: ignore, it was part of another comment that got deleted once I saw you were using a recursive lock

File: Sources/WhoopDIKit/Container/ThreadSafeDependencyGraph.swift [hunk 9]
```diff
@@ -0,0 +1,35 @@
+import Foundation
+
+final class ThreadSafeDependencyGraph: Sendable {
+    private let lock = NSRecursiveLock()
+    nonisolated(unsafe) private let serviceDict: ServiceDictionary<DependencyDefinition> = .init()
```
Comment (jrosen081) [inline Sources/WhoopDIKit/Container/ThreadSafeDependencyGraph.swift:5]: let's not make this `nonisolated(unsafe)`, but instead make the class `@unchecked Sendable` since that is more accurate to our usage here

File: Tests/WhoopDIKitTests/Container/ContainerTests.swift [hunk 10]
```diff
@@ -1,60 +1,91 @@
...
+        // performing a local inject. 1000 times should do the trick.
+        container.registerModules(modules: [GoodTestModule()])
+        
+        Task.detached {
+            let _: Dependency = self.container.inject("C_Factory") { module in
+                module.factory(name: "C_Factory") { DependencyA() as Dependency }
+            }
+        }
+        
+        Task.detached {
```
Comment (jrosen081) [inline Tests/WhoopDIKitTests/Container/ContainerTests.swift:57]: I think we should store both of these and await their values so we are certain that we can be certain these run. We also could do a for loop in each one of those so that we can get it to crash every time?

File: Sources/WhoopDIKit/Container/ThreadSafeDependencyGraph.swift (hunk 9 above)
Comment (ncipollo) [reply Sources/WhoopDIKit/Container/ThreadSafeDependencyGraph.swift:5]: Could you elaborate on why `unchecked Sendable` is preferable here? My rationale is that I wanted to scope this check down to just this variable since that is the only thing which is unsafe. If we were to make that a Sendable in the future we could remove this all together.

File: Tests/WhoopDIKitTests/Container/ContainerTests.swift (hunk 10 above)
Comment (ncipollo) [reply Tests/WhoopDIKitTests/Container/ContainerTests.swift:57]: That is what I had in here originally 🙃

File: Sources/WhoopDIKit/Container/ThreadSafeDependencyGraph.swift (hunk 9 above)
Comment (jrosen081) [reply Sources/WhoopDIKit/Container/ThreadSafeDependencyGraph.swift:5]: In the way I see it, we are providing the guarantee that the `ThreadSafeDependencyGraph` is sendable, since we are providing locking around the non-sendable type. This to me means that this type is `@unchecked Sendable` because we are providing this guarantee to tell the compiler. From my understanding, `nonisolated(unsafe)` is more of an escape hatch where we _know_ something won't race, but the compiler can't reason about it (but we don't really need to do anything, where here we are doing something to make it Sendable)
